CLASSES:
- airplane
- automobile
- bird
- cat
- deer
- dog
- frog
- horse
- ship
- truck
DATA_FORMAT: NHWC
IMAGE_SIZE:
- 32
- 32
POST_PROCESSOR: null
PRE_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
  processors:
  - !!python/object:lmnet.pre_processor.Resize
    size:
    - 32
    - 32
  - !!python/object:lmnet.pre_processor.DivideBy255 {}
TASK: IMAGE.CLASSIFICATION
