CLASSES:
- '0'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
DATA_FORMAT: NHWC
IMAGE_SIZE:
- 128
- 128
POST_PROCESSOR: null
PRE_PROCESSOR:
- Resize:
    size:
    - 128
    - 128
- DivideBy255: null
TASK: IMAGE.CLASSIFICATION
